apply plugin: 'com.android.test'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace = "com.ysferencakir.paperlike.benchmark"
    compileSdk = rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk = 29
        targetSdk = rootProject.ext.targetSdkVersion
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    targetProjectPath = ":app"
    experimentalProperties["android.experimental.self-instrumenting"] = true

    buildTypes {
        benchmark {
            debuggable = true
            signingConfig = signingConfigs.debug
            matchingFallbacks = ['release']
        }
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

androidComponents {
    beforeVariants(selector().all()) { variantBuilder ->
        variantBuilder.enable = variantBuilder.buildType == "benchmark"
    }
}

dependencies {
    implementation "androidx.benchmark:benchmark-macro-junit4:1.4.1"
    implementation "androidx.test.ext:junit:$androidxJunitVersion"
    implementation "androidx.test.uiautomator:uiautomator:2.3.0"
    implementation "androidx.core:core:$androidxCoreVersion"
}
